CREATE TABLE IF NOT EXISTS "sf3archive_matches" (
	"id" serial PRIMARY KEY NOT NULL,
	"video" varchar(256),
	"time_stamped_hours" integer,
	"time_stamped_minutes" integer,
	"time_stamped_seconds" integer,
	"starting_seconds" integer,
	"hyperlink_seconds" varchar(256),
	"player_one_name" varchar(256),
	"player_one_char" varchar(256),
	"player_one_s_a" varchar(256),
	"player_one_win_loss" boolean,
	"player_two_name" varchar(256),
	"player_two_char" varchar(256),
	"player_two_s_a" varchar(256),
	"player_two_win_loss" boolean,
	"player_one_perfect" integer,
	"player_two_perfect" integer,
	"mirror" integer,
	"event" varchar(256),
	"type" varchar(256),
	"date" integer,
	"location" varchar(256),
	"breakdown" varchar(256),
	"version" varchar(256),
	"yt_description" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
